export const FETCHQUIZ = 'FETCHQUIZ';
export const STARTQUIZ = 'STARTQUIZ';
export const PLAYAGAIN = 'PLAYAGAIN';

export const GETREADY = 'GETREADY';
export const STARTCOUNTDOWN = 'STARTCOUNTDOWN';

export const ANSWERED_CORRECT = 'ANSWERED_CORRECT'
export const ANSWERED_WRONG = 'ANSWERED_WRONG'


